### ISSUE TITLE
App is crashing.

### ISSUE THREAD

**Issue by Aravind-Rajendran** [vincentjames501/libvorbis-libogg-android#15]
i am using proguard in android studio.app is crashing in encodefeed class

**Comment by vincentjames501** [comment]
Make sure your ProGuard settings don't obfuscate the encodefeed class or any other class that has JNI bindings.

**Comment by Aravind-Rajendran** [comment]
i have tried  something like that
 keep org.xiph.vorbis.encoder.VorbisEncoder.**

but it does not work out.something wrong?

**Comment by Aravind-Rajendran** [comment]
thanks i fixed it

**Comment by Aravind-Rajendran** [comment]
for fyi


-keepclasseswithmember class * {
    native <methods>;
}

-keep public class org.xiph.vorbis.**{
public *;
}
